# TPM: manages all plugins below. Must be listed first.
set -g @plugin 'tmux-plugins/tpm'

# Sensible defaults: UTF-8, 50k scrollback, faster escape time, etc.
set -g @plugin 'tmux-plugins/tmux-sensible'

# Resurrect: manually save (prefix+Ctrl+s) and restore (prefix+Ctrl+r) sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Continuum: auto-saves your session every 15min using resurrect
set -g @plugin 'tmux-plugins/tmux-continuum'

# Change prefix from Ctrl+B (default) to Ctrl+T easier to reach
unbind C-b
set-option -g prefix C-t
bind-key C-t send-prefix

# When restoring, also reopen vim/neovim with their saved sessions
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

run '~/.tmux/plugins/tpm/tpm'
